packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

injectWorkspacePackages: true
disallowWorkspaceCycles: true
saveWorkspaceProtocol: true
allowBuilds:
  '@prisma/engines': false
  prisma: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - e2b@2.38.3
